spring.application.name=demo
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.dogajuakxpyopcyehugd&password=a20204cs10534
spring.datasource.hikari.connection-timeout=30000